name: End-to-end tests
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # - name: Install Yarn
      # run: npm install -g yarn

      - name: Build
        run: yarn build

      - name: Cypress run
        uses: cypress-io/github-action@v4.1.0
        with:
          working-directory: apps/web
          config-file: ./cypress.config.ts
          start: yarn start:e2e
          spec: ./cypress/e2e/**/*.cy.js
